### PR TITLE
Added service and command syntax

### PR DESCRIPTION
**Pull request by jhalbrecht**
Added simple examples of Nagios .cfg service and command syntax.

### CODE REVIEW

**Comment by jpmens** [comment]
Just as I was going to look at this, I saw your e-mail. All this (and what you write) looks good. Shall I merge this or do you want to re-do the pull request? (You can also force-push your changes; as long as this is open, they'll be added to this PR)

**Comment by jhalbrecht** [comment]
Interesting, my learning something new for the day is the merged pull request. Let's see if it works.

**Comment by jhalbrecht** [comment]
I updated the pull request with the new --ignoreping option.

**Comment by jpmens** [comment]
Merged, thanks!

**Pull request merged**
